# Generated by Django 5.1.2 on 2024-10-15 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='', max_length=100)),
                ('business_email', models.EmailField(default='', max_length=254)),
                ('business_owner', models.CharField(default='', max_length=100)),
                ('tax_identification_number', models.CharField(default='', max_length=20)),
                ('business_history', models.TextField(default='')),
                ('ownership_structure', models.TextField(default='')),
                ('loan_amount', models.IntegerField(default=0)),
                ('loan_timeframe', models.IntegerField(default=0)),
                ('purpose', models.TextField(default='')),
                ('revenue', models.IntegerField(default=0)),
                ('reduce_water', models.BooleanField(default=False)),
                ('reduce_water_value', models.PositiveIntegerField(blank=True, null=True)),
                ('reduce_electricity', models.BooleanField(default=False)),
                ('reduce_electricity_value', models.PositiveIntegerField(blank=True, null=True)),
                ('reduce_waste', models.BooleanField(default=False)),
                ('reduce_waste_value', models.PositiveIntegerField(blank=True, null=True)),
                ('energy_efficient_lightbulbs', models.BooleanField(default=False)),
                ('energy_efficient_lightbulbs_value', models.PositiveIntegerField(blank=True, null=True)),
                ('reduce_co2', models.BooleanField(default=False)),
                ('reduce_co2_value', models.PositiveIntegerField(blank=True, null=True)),
                ('loan_terms', models.TextField(blank=True, null=True)),
                ('loan_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_increasemiss1', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_increasemiss2', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_increasemiss3', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
