# Generated by Django 4.1.13 on 2024-10-06 00:11

import bson.objectid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('revenue', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('reduce_water', models.BooleanField(default=False)),
                ('reduce_water_value', models.PositiveIntegerField(blank=True, null=True)),
                ('reduce_electricity', models.BooleanField(default=False)),
                ('reduce_electricity_value', models.PositiveIntegerField(blank=True, null=True)),
                ('reduce_waste', models.BooleanField(default=False)),
                ('reduce_waste_value', models.PositiveIntegerField(blank=True, null=True)),
                ('energy_efficient_lightbulbs', models.BooleanField(default=False)),
                ('energy_efficient_lightbulbs_value', models.PositiveIntegerField(blank=True, null=True)),
                ('reduce_co2', models.BooleanField(default=False)),
                ('reduce_co2_value', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
