# Generated by Django 4.1.13 on 2024-10-06 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_alter_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='business_email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='description',
            new_name='business_history',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='business_name',
        ),
        migrations.AddField(
            model_name='client',
            name='business_owner',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='loan_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='loan_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='loan_timeframe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='ownership_structure',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='purpose',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_identification_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
