# Generated by Django 4.1.13 on 2024-10-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_email_client_business_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='loan_increasemiss1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='loan_increasemiss2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='loan_increasemiss3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='loan_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
